package computerdatabase

import scala.concurrent.duration._

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import io.gatling.jdbc.Predef._

class MytaskwidgetYourapproval extends Simulation {

	val httpProtocol = http
		.baseUrl("https://us-development.gomercatus.com")
		.inferHtmlResources(BlackList(""".*\.js""", """.*\.css""", """.*\.gif""", """.*\.jpeg""", """.*\.jpg""", """.*\.ico""", """.*\.woff""", """.*\.(t|o)tf""", """.*\.png"""), WhiteList())
		.acceptHeader("*/*")
		.acceptEncodingHeader("gzip, deflate")
		.acceptLanguageHeader("en-US,en;q=0.5")
		.userAgentHeader("Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0")

	val headers_0 = Map("Accept" -> "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8")

	val headers_3 = Map(
		"Accept" -> "application/json, text/javascript, */*; q=0.01",
		"X-Requested-With" -> "XMLHttpRequest")

	val headers_5 = Map(
		"Accept" -> "text/plain, */*; q=0.01",
		"Content-Type" -> "text/plain;charset=UTF-8",
		"X-Requested-With" -> "XMLHttpRequest")

	val headers_11 = Map(
		"Accept" -> "application/json",
		"Content-Type" -> "application/json; charset=utf-8",
		"X-Requested-With" -> "XMLHttpRequest")

	val headers_12 = Map(
		"Content-Type" -> "application/json;charset=UTF-8",
		"X-Requested-With" -> "XMLHttpRequest")



	val scn = scenario("MytaskwidgetYourapproval")
		// Login
		.exec(http("MytaskwidgetYourapproval_0")
			.get("/")
			.headers(headers_0))
		.pause(33)
		// EnterUserId
		.exec(http("MytaskwidgetYourapproval_1")
			.post("/external/getUserAuthType")
			.headers(headers_0)
			.formParam("userName", "user2@testqa1.com")
	)
		.pause(5)
		.exec(http("MytaskwidgetYourapproval_2")
			.post("/j_spring_security_check")
			.headers(headers_0)
			.formParam("j_username", "user2@testqa1.com")
			.formParam("j_password", "Test@12345"))
		.pause(1)
		.exec(http("MytaskwidgetYourapproval_3")
			.get("/rest/userInfo?_=1548765846406")
			.headers(headers_3)
			.resources(http("MytaskwidgetYourapproval_4")
			.get("/rest/orgs/organization/logo/download/?ts=1548765850225")
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0004_response.txt"))),
            http("MytaskwidgetYourapproval_5")
			.get("/app/js/libs/i18bundle/Messages.properties?_=1548765846407")
			.headers(headers_5)
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0005_response.txt"))),
            http("MytaskwidgetYourapproval_6")
			.get("/app/js/libs/i18bundle/Messages_en.properties?_=1548765846408")
			.headers(headers_5)
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0006_response.txt"))),
            http("MytaskwidgetYourapproval_7")
			.get("/app/js/libs/i18bundle/Messages_en-US.properties?_=1548765846409")
			.headers(headers_5)
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0007_response.txt"))),
            http("MytaskwidgetYourapproval_8")
			.get("/rest/userInfo/userLocalizationConfig?_=1548765846410")
			.headers(headers_3)
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0008_response.txt"))),
            http("MytaskwidgetYourapproval_9")
			.get("/rest/assets/assetConfig?_=1548765846411")
			.headers(headers_3)
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0009_response.txt"))),
            http("MytaskwidgetYourapproval_10")
			.get("/rest/userInfo/photo/download/?ts=1548765853027&scaleHeight=140&scaleWidth=140"),
            http("MytaskwidgetYourapproval_11")
			.get("/rest/wfTaskApproval/myTask/count?ts=1548765852548&_=1548765846412")
			.headers(headers_11)
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0011_response.txt"))),
            http("MytaskwidgetYourapproval_12")
			.post("/cometd/handshake")
			.headers(headers_12)
			.body(RawFileBody("MytaskwidgetYourapproval_0012_request.txt"))
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0012_response.txt"))),
            http("MytaskwidgetYourapproval_13")
			.post("/cometd/connect")
			.headers(headers_12)
			.body(RawFileBody("MytaskwidgetYourapproval_0013_request.txt"))
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0013_response.txt"))),
            http("MytaskwidgetYourapproval_14")
			.get("/rest/assetHomePage/3061?_=1548765846413")
			.headers(headers_3)
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0014_response.txt"))),
            http("MytaskwidgetYourapproval_15")
			.post("/cometd/connect")
			.headers(headers_12)
			.body(RawFileBody("MytaskwidgetYourapproval_0015_request.txt"))
			.check(status.is(500))
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0015_response.txt"))),
            http("MytaskwidgetYourapproval_16")
			.get("/rest/assetTile/globalCalendar/3061?_=1548765846414")
			.headers(headers_3)
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0016_response.txt"))),
            http("MytaskwidgetYourapproval_17")
			.post("/cometd/connect")
			.headers(headers_12)
			.body(RawFileBody("MytaskwidgetYourapproval_0017_request.txt"))
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0017_response.txt"))),
            http("MytaskwidgetYourapproval_18")
			.get("/rest/wfTask/A/globalTasks/3061?_=1548765846415")
			.headers(headers_3)
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0018_response.txt"))),
            http("MytaskwidgetYourapproval_19")
			.post("/cometd/")
			.headers(headers_12)
			.body(RawFileBody("MytaskwidgetYourapproval_0019_request.txt"))
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0019_response.txt"))))
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0003_response.txt"))))
		.pause(1)
		.exec(http("MytaskwidgetYourapproval_20")
			.post("/cometd/connect")
			.headers(headers_12)
			.body(RawFileBody("MytaskwidgetYourapproval_0020_request.txt"))
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0020_response.txt"))))
		.pause(2)
		.exec(http("MytaskwidgetYourapproval_21")
			.post("/cometd/connect")
			.headers(headers_12)
			.body(RawFileBody("MytaskwidgetYourapproval_0021_request.txt"))
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0021_response.txt"))))
		.pause(2)
		.exec(http("MytaskwidgetYourapproval_22")
			.post("/cometd/connect")
			.headers(headers_12)
			.body(RawFileBody("MytaskwidgetYourapproval_0022_request.txt"))
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0022_response.txt"))))
		.pause(2)
		.exec(http("MytaskwidgetYourapproval_23")
			.post("/cometd/connect")
			.headers(headers_12)
			.body(RawFileBody("MytaskwidgetYourapproval_0023_request.txt"))
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0023_response.txt"))))
		.pause(2)
		// NavigateToTabMyTasks
		.exec(http("MytaskwidgetYourapproval_24")
			.post("/cometd/connect")
			.headers(headers_12)
			.body(RawFileBody("MytaskwidgetYourapproval_0024_request.txt"))
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0024_response.txt"))))
		.pause(2)
		.exec(http("MytaskwidgetYourapproval_25")
			.post("/cometd/connect")
			.headers(headers_12)
			.body(RawFileBody("MytaskwidgetYourapproval_0025_request.txt"))
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0025_response.txt"))))
		.pause(1)
		.exec(http("MytaskwidgetYourapproval_26")
			.get("/rest/wfTask/GLOBAL_TASK_LIST/taskResources/609?_=1548765846416")
			.headers(headers_3)
			.resources(http("MytaskwidgetYourapproval_27")
			.get("/rest/wfTask/GLOBAL_TASK_VIEW/views?_=1548765846417")
			.headers(headers_11)
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0027_response.txt"))),
            http("MytaskwidgetYourapproval_28")
			.post("/cometd/connect")
			.headers(headers_12)
			.body(RawFileBody("MytaskwidgetYourapproval_0028_request.txt"))
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0028_response.txt"))),
            http("MytaskwidgetYourapproval_29")
			.get("/rest/wfTask/GLOBAL_TASK_LIST/filterConfig?_=1548765846418")
			.headers(headers_11)
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0029_response.txt"))),
            http("MytaskwidgetYourapproval_30")
			.get("/rest/wfTask/GLOBAL_TASK_LIST/filters?_=1548765846419")
			.headers(headers_11)
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0030_response.txt"))))
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0026_response.txt"))))
		.pause(1)
		.exec(http("MytaskwidgetYourapproval_31")
			.post("/cometd/connect")
			.headers(headers_12)
			.body(RawFileBody("MytaskwidgetYourapproval_0031_request.txt"))
			.resources(http("MytaskwidgetYourapproval_32")
			.post("/rest/wfTaskApproval/globalMyTask")
			.headers(headers_11)
			.body(RawFileBody("MytaskwidgetYourapproval_0032_request.txt"))
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0032_response.txt"))))
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0031_response.txt"))))
		.pause(1)
		.exec(http("MytaskwidgetYourapproval_33")
			.post("/cometd/connect")
			.headers(headers_12)
			.body(RawFileBody("MytaskwidgetYourapproval_0033_request.txt"))
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0033_response.txt"))))
		.pause(2)
		.exec(http("MytaskwidgetYourapproval_34")
			.post("/cometd/connect")
			.headers(headers_12)
			.body(RawFileBody("MytaskwidgetYourapproval_0034_request.txt"))
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0034_response.txt"))))
		.pause(2)
		.exec(http("MytaskwidgetYourapproval_35")
			.post("/cometd/connect")
			.headers(headers_12)
			.body(RawFileBody("MytaskwidgetYourapproval_0035_request.txt"))
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0035_response.txt"))))
		.pause(2)
		.exec(http("MytaskwidgetYourapproval_36")
			.post("/cometd/connect")
			.headers(headers_12)
			.body(RawFileBody("MytaskwidgetYourapproval_0036_request.txt"))
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0036_response.txt"))))
		.pause(2)
		.exec(http("MytaskwidgetYourapproval_37")
			.post("/cometd/connect")
			.headers(headers_12)
			.body(RawFileBody("MytaskwidgetYourapproval_0037_request.txt"))
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0037_response.txt"))))
		.pause(2)
		// SelectOptionAllTasks
		.exec(http("MytaskwidgetYourapproval_38")
			.post("/cometd/connect")
			.headers(headers_12)
			.body(RawFileBody("MytaskwidgetYourapproval_0038_request.txt"))
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0038_response.txt"))))
		.pause(2)
		.exec(http("MytaskwidgetYourapproval_39")
			.post("/cometd/connect")
			.headers(headers_12)
			.body(RawFileBody("MytaskwidgetYourapproval_0039_request.txt"))
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0039_response.txt"))))
		.pause(2)
		.exec(http("MytaskwidgetYourapproval_40")
			.post("/cometd/connect")
			.headers(headers_12)
			.body(RawFileBody("MytaskwidgetYourapproval_0040_request.txt"))
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0040_response.txt"))))
		.pause(2)
		.exec(http("MytaskwidgetYourapproval_41")
			.post("/cometd/connect")
			.headers(headers_12)
			.body(RawFileBody("MytaskwidgetYourapproval_0041_request.txt"))
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0041_response.txt"))))
		.pause(2)
		.exec(http("MytaskwidgetYourapproval_42")
			.post("/cometd/connect")
			.headers(headers_12)
			.body(RawFileBody("MytaskwidgetYourapproval_0042_request.txt"))
			.resources(http("MytaskwidgetYourapproval_43")
			.post("/rest/wfTaskApproval/globalMyTask")
			.headers(headers_11)
			.body(RawFileBody("MytaskwidgetYourapproval_0043_request.txt"))
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0043_response.txt"))),
            http("MytaskwidgetYourapproval_44")
			.post("/cometd/connect")
			.headers(headers_12)
			.body(RawFileBody("MytaskwidgetYourapproval_0044_request.txt"))
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0044_response.txt"))))
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0042_response.txt"))))
		.pause(2)
		.exec(http("MytaskwidgetYourapproval_45")
			.post("/cometd/connect")
			.headers(headers_12)
			.body(RawFileBody("MytaskwidgetYourapproval_0045_request.txt"))
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0045_response.txt"))))
		.pause(2)
		.exec(http("MytaskwidgetYourapproval_46")
			.post("/cometd/connect")
			.headers(headers_12)
			.body(RawFileBody("MytaskwidgetYourapproval_0046_request.txt"))
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0046_response.txt"))))
		.pause(2)
		.exec(http("MytaskwidgetYourapproval_47")
			.post("/cometd/connect")
			.headers(headers_12)
			.body(RawFileBody("MytaskwidgetYourapproval_0047_request.txt"))
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0047_response.txt"))))
		.pause(2)
		// ScrollDown
		.exec(http("MytaskwidgetYourapproval_48")
			.post("/cometd/connect")
			.headers(headers_12)
			.body(RawFileBody("MytaskwidgetYourapproval_0048_request.txt"))
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0048_response.txt"))))
		.pause(2)
		.exec(http("MytaskwidgetYourapproval_49")
			.post("/cometd/connect")
			.headers(headers_12)
			.body(RawFileBody("MytaskwidgetYourapproval_0049_request.txt"))
			.resources(http("MytaskwidgetYourapproval_50")
			.post("/rest/wfTaskApproval/globalMyTask")
			.headers(headers_11)
			.body(RawFileBody("MytaskwidgetYourapproval_0050_request.txt"))
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0050_response.txt"))),
            http("MytaskwidgetYourapproval_51")
			.post("/cometd/connect")
			.headers(headers_12)
			.body(RawFileBody("MytaskwidgetYourapproval_0051_request.txt"))
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0051_response.txt"))))
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0049_response.txt"))))
		.pause(2)
		.exec(http("MytaskwidgetYourapproval_52")
			.post("/cometd/connect")
			.headers(headers_12)
			.body(RawFileBody("MytaskwidgetYourapproval_0052_request.txt"))
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0052_response.txt"))))
		.pause(2)
		.exec(http("MytaskwidgetYourapproval_53")
			.post("/cometd/connect")
			.headers(headers_12)
			.body(RawFileBody("MytaskwidgetYourapproval_0053_request.txt"))
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0053_response.txt"))))
		.pause(2)
		.exec(http("MytaskwidgetYourapproval_54")
			.post("/cometd/connect")
			.headers(headers_12)
			.body(RawFileBody("MytaskwidgetYourapproval_0054_request.txt"))
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0054_response.txt"))))
		.pause(2)
		.exec(http("MytaskwidgetYourapproval_55")
			.post("/cometd/connect")
			.headers(headers_12)
			.body(RawFileBody("MytaskwidgetYourapproval_0055_request.txt"))
			.check(bodyBytes.is(RawFileBody("MytaskwidgetYourapproval_0055_response.txt"))))
		.pause(783 milliseconds)
		// Stop

	setUp(scn.inject(atOnceUsers(1))).protocols(httpProtocol)
}