package createnote

import scala.concurrent.duration._

import io.gatling.core.Predef._
import io.gatling.http.Predef._
import io.gatling.jdbc.Predef._

class CreateNotes3 extends Simulation {

	val httpProtocol = http
		.baseUrl("https://us-release.gomercatus.com")
		.disableAutoReferer
		.userAgentHeader("Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:47.0) Gecko/20100101 Firefox/47.0")

	val headers_0 = Map(
		"Accept" -> "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
		"Accept-Encoding" -> "gzip, deflate, br",
		"Accept-Language" -> "en-US,en;q=0.5",
		"Referer" -> "https://us-release.gomercatus.com/")

	val headers_1 = Map(
		"Accept" -> "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
		"Accept-Encoding" -> "gzip, deflate, br",
		"Accept-Language" -> "en-US,en;q=0.5",
		"Referer" -> "https://us-release.gomercatus.com/login.jsp?userName=kamlesh.zanjad@synerzip.com")

	val headers_2 = Map(
		"Accept" -> "application/json, text/javascript, */*; q=0.01",
		"Accept-Encoding" -> "gzip, deflate, br",
		"Accept-Language" -> "en-US,en;q=0.5",
		"Referer" -> "https://us-release.gomercatus.com/index.html",
		"X-Requested-With" -> "XMLHttpRequest")

	val headers_3 = Map(
		"Accept" -> "text/plain, */*; q=0.01",
		"Accept-Encoding" -> "gzip, deflate, br",
		"Accept-Language" -> "en-US,en;q=0.5",
		"Content-Type" -> "text/plain;charset=UTF-8",
		"Referer" -> "https://us-release.gomercatus.com/index.html",
		"X-Requested-With" -> "XMLHttpRequest")

	val headers_8 = Map(
		"Accept" -> "*/*",
		"Accept-Encoding" -> "gzip, deflate, br",
		"Accept-Language" -> "en-US,en;q=0.5",
		"Referer" -> "https://us-release.gomercatus.com/index.html")

	val headers_9 = Map(
		"Accept" -> "*/*",
		"Accept-Encoding" -> "gzip, deflate, br",
		"Accept-Language" -> "en-US,en;q=0.5",
		"Content-Type" -> "application/json;charset=UTF-8",
		"Referer" -> "https://us-release.gomercatus.com/index.html",
		"X-Requested-With" -> "XMLHttpRequest")

	val headers_10 = Map(
		"Accept" -> "application/json",
		"Accept-Encoding" -> "gzip, deflate, br",
		"Accept-Language" -> "en-US,en;q=0.5",
		"Content-Type" -> "application/json; charset=utf-8",
		"Referer" -> "https://us-release.gomercatus.com/index.html",
		"X-Requested-With" -> "XMLHttpRequest")

	val headers_39 = Map(
		"Proxy-Connection" -> "Keep-Alive",
		"User-Agent" -> "Microsoft-WNS/10.0")

    val uri2 = "http://tile-service.weather.microsoft.com/en-US/livetile/preinstall"

	val chain_0 = // Login
		exec(http("request_0")
			.post("/external/getUserAuthType")
			.headers(headers_0)
			.formParam("userName", "kamlesh.zanjad@synerzip.com"))
		.pause(6)
		.exec(http("request_1")
			.post("/j_spring_security_check")
			.headers(headers_1)
			.formParam("j_username", "kamlesh.zanjad@synerzip.com")
			.formParam("j_password", "Test@12345"))
		.pause(484 milliseconds)
		.exec(http("request_2")
			.get("/rest/userInfo?_=1547812711572")
			.headers(headers_2))
		.pause(294 milliseconds)
		.exec(http("request_3")
			.get("/app/js/libs/i18bundle/Messages.properties?_=1547812711573")
			.headers(headers_3))
		.pause(117 milliseconds)
		.exec(http("request_4")
			.get("/app/js/libs/i18bundle/Messages_en.properties?_=1547812711574")
			.headers(headers_3))
		.exec(http("request_5")
			.get("/app/js/libs/i18bundle/Messages_en-US.properties?_=1547812711575")
			.headers(headers_3))
		.exec(http("request_6")
			.get("/rest/userInfo/userLocalizationConfig?_=1547812711576")
			.headers(headers_2))
		.exec(http("request_7")
			.get("/rest/assets/assetConfig?_=1547812711577")
			.headers(headers_2))
		.pause(109 milliseconds)
		.exec(http("request_8")
			.get("/rest/userInfo/photo/download/?ts=1547812717088&scaleHeight=140&scaleWidth=140")
			.headers(headers_8))
		.exec(http("request_9")
			.post("/cometd/handshake")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0009_request.txt")))
		.exec(http("request_10")
			.get("/rest/wfTaskApproval/myTask/count?ts=1547812716241&_=1547812711578")
			.headers(headers_10))
		.exec(http("request_11")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0011_request.txt")))
		.exec(http("request_12")
			.get("/rest/assetHomePage/3341?_=1547812711579")
			.headers(headers_2))
		.exec(http("request_13")
			.get("/rest/assetTile/globalCalendar/3341?_=1547812711580")
			.headers(headers_2))
		.exec(http("request_14")
			.get("/rest/wfTask/A/globalTasks/3341?_=1547812711581")
			.headers(headers_2))
		.pause(326 milliseconds)
		.exec(http("request_15")
			.post("/cometd/")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0015_request.txt")))
		.pause(671 milliseconds)
		.exec(http("request_16")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0016_request.txt")))
		.pause(2)
		// SelectProject
		.exec(http("request_17")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0017_request.txt")))
		.pause(2)
		.exec(http("request_18")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0018_request.txt")))
		.pause(488 milliseconds)
		.exec(http("request_19")
			.get("/rest/wfTask/P/settings/org/637/includeWeekend?_=1547812711582")
			.headers(headers_2))
		.exec(http("request_20")
			.get("/rest/assumptionPermission/userPermission?_=1547812711583")
			.headers(headers_10))
		.pause(157 milliseconds)
		.exec(http("request_21")
			.post("/rest/projects/637")
			.headers(headers_10)
			.body(RawFileBody("CreateNotes3_0021_request.txt")))
		.exec(http("request_22")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0022_request.txt")))
		.pause(2)
		.exec(http("request_23")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0023_request.txt")))
		.pause(2)
		.exec(http("request_24")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0024_request.txt")))
		.pause(2)
		.exec(http("request_25")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0025_request.txt")))
		.pause(2)
		.exec(http("request_26")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0026_request.txt")))
		.pause(2)
		.exec(http("request_27")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0027_request.txt")))
		.pause(2)
		.exec(http("request_28")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0028_request.txt")))
		.pause(2)
		.exec(http("request_29")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0029_request.txt")))
		.pause(2)
		.exec(http("request_30")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0030_request.txt")))
		.pause(2)
		.exec(http("request_31")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0031_request.txt")))
		.pause(2)
		.exec(http("request_32")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0032_request.txt")))
		.pause(2)
		.exec(http("request_33")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0033_request.txt")))
		.pause(2)
		.exec(http("request_34")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0034_request.txt")))
		.pause(2)
		.exec(http("request_35")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0035_request.txt")))
		.pause(2)
		.exec(http("request_36")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0036_request.txt")))
		.pause(2)
		.exec(http("request_37")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0037_request.txt")))
		.pause(2)
		.exec(http("request_38")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0038_request.txt")))
		.pause(1)
		.exec(http("request_39")
			.get(uri2 + "?region=US&appid=C98EA5B0842DBB9405BBF071E1DA76512D21FE36&FORM=Threshold")
			.headers(headers_39))
		.pause(363 milliseconds)
		.exec(http("request_40")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0040_request.txt")))
		.pause(2)
		.exec(http("request_41")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0041_request.txt")))
		.pause(2)
		.exec(http("request_42")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0042_request.txt")))
		.pause(2)
		.exec(http("request_43")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0043_request.txt")))
		.pause(2)
		.exec(http("request_44")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0044_request.txt")))
		.pause(2)
		.exec(http("request_45")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0045_request.txt")))
		.pause(2)
		.exec(http("request_46")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0046_request.txt")))
		.pause(2)
		.exec(http("request_47")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0047_request.txt")))
		.pause(2)
		.exec(http("request_48")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0048_request.txt")))
		.pause(2)
		.exec(http("request_49")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0049_request.txt")))
		.pause(2)
		.exec(http("request_50")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0050_request.txt")))
		.pause(2)
		.exec(http("request_51")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0051_request.txt")))
		.pause(2)
		.exec(http("request_52")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0052_request.txt")))
		.pause(2)
		// SelectProject
		.exec(http("request_53")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0053_request.txt")))
		.exec(http("request_54")
			.get("/rest/users/adminOrgUsers/637?_=1547812711584")
			.headers(headers_2))

val chain_1 = pause(103 milliseconds)
		.exec(http("request_55")
			.get("/rest/summary/23921?_=1547812711585")
			.headers(headers_2))
		.exec(http("request_56")
			.get("/rest/summary/summaryGraph/23921?_=1547812711586")
			.headers(headers_2))
		.pause(209 milliseconds)
		.exec(http("request_57")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0057_request.txt")))
		.pause(2)
		.exec(http("request_58")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0058_request.txt")))
		.pause(2)
		.exec(http("request_59")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0059_request.txt")))
		.pause(2)
		.exec(http("request_60")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0060_request.txt")))
		.pause(2)
		.exec(http("request_61")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0061_request.txt")))
		.pause(2)
		.exec(http("request_62")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0062_request.txt")))
		.pause(2)
		.exec(http("request_63")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0063_request.txt")))
		.pause(2)
		.exec(http("request_64")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0064_request.txt")))
		.pause(2)
		.exec(http("request_65")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0065_request.txt")))
		.pause(2)
		.exec(http("request_66")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0066_request.txt")))
		.pause(2)
		.exec(http("request_67")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0067_request.txt")))
		.pause(2)
		.exec(http("request_68")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0068_request.txt")))
		.pause(2)
		.exec(http("request_69")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0069_request.txt")))
		.pause(2)
		.exec(http("request_70")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0070_request.txt")))
		.pause(2)
		.exec(http("request_71")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0071_request.txt")))
		.pause(2)
		.exec(http("request_72")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0072_request.txt")))
		.pause(2)
		.exec(http("request_73")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0073_request.txt")))
		.pause(2)
		.exec(http("request_74")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0074_request.txt")))
		.pause(2)
		.exec(http("request_75")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0075_request.txt")))
		.pause(2)
		.exec(http("request_76")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0076_request.txt")))
		.pause(2)
		.exec(http("request_77")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0077_request.txt")))
		.pause(2)
		.exec(http("request_78")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0078_request.txt")))
		.pause(2)
		.exec(http("request_79")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0079_request.txt")))
		.pause(2)
		.exec(http("request_80")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0080_request.txt")))
		.pause(2)
		.exec(http("request_81")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0081_request.txt")))
		.pause(2)
		.exec(http("request_82")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0082_request.txt")))
		.pause(2)
		.exec(http("request_83")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0083_request.txt")))
		.pause(2)
		.exec(http("request_84")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0084_request.txt")))
		.pause(2)
		.exec(http("request_85")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0085_request.txt")))
		.pause(2)
		.exec(http("request_86")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0086_request.txt")))
		.pause(2)
		.exec(http("request_87")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0087_request.txt")))
		.pause(2)
		.exec(http("request_88")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0088_request.txt")))
		.pause(2)
		.exec(http("request_89")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0089_request.txt")))
		.pause(2)
		.exec(http("request_90")
			.post("/cometd/connect")
			.headers(headers_9)
			.body(RawFileBody("CreateNotes3_0090_request.txt")))

	val scn = scenario("CreateNotes3").exec(
		chain_0, chain_1)

	setUp(scn.inject(atOnceUsers(1))).protocols(httpProtocol)
}